import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const media=read('admin-media.js');
const form=read('admin-product-form.js');
const imp=read('admin-import.js');
const sync=read('public-sync.js');
const app=read('app.js');
const products=read('admin-products.js');

assert.match(media,/1400/);
assert.match(media,/480/);
assert.match(media,/\.l\.webp/);
assert.match(media,/\.s\.webp/);
assert.match(media,/uploadProductImagePair/);
assert.match(form,/uploadProductImagePair/);
assert.match(imp,/uploadProductImagePair/);
assert.match(sync,/image_thumb:imageUrl\(productThumbnailPath\(primaryPath\)\)/);
assert.match(sync,/thumb:imageUrl\(productThumbnailPath\(row\.image_path\)\)/);
assert.match(app,/image\.src = item\.image_thumb \|\| item\.image/);
assert.match(app,/image\.src = target\.thumb \|\| target\.image/);
assert.match(app,/image\.loading = imageLoading/);
assert.match(app,/image\.decoding = 'async'/);
assert.match(products,/loading="lazy" decoding="async"/);
assert.match(products,/thumbnail fallback/);
assert.match(products,/copy\(clean,thumbTarget\)/);
console.log('THUMBNAILS_OK');
